name: ci

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - run: npm ci
      - run: npm run lint

  karma:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - run: npm ci
      - run: npx playwright install-deps
      - run: npx run-s init bundle test-unit-karma

  tests:
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 16.13
          - 18.12
          - 19
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      # https://github.com/npm/cli/issues/2971
      - run: npm i npm@$(node -pe "require('./package').devDependencies.npm") -g --no-audit --no-fund --loglevel=error
      - run: npm ci
      - run: npx run-s init bundle test-unit-node test-entries test-compat-tools test-builder

  promises-and-observables:
    needs: tests
    strategy:
      matrix:
        node:
          - 16.13
          - 18.12
          - 19
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npx run-s init test-promises test-observables
