name: ci

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - run: npm ci
      - run: npm run lint

  karma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - run: npm ci
      - run: npx run-s init bundle test-unit-karma

  promises-and-observables:
    strategy:
      matrix:
        node:
          - 16.13
          - 18.12
          - 19
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npx run-s init test-promises test-observables

  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 16.13
          - 18.12
          - 19
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npx run-s init bundle test-unit-node test-entries test-compat-data test-compat-tools test-builder

  bun:
    strategy:
      matrix:
        bun:
          - 0.3
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: ${{ matrix.bun }}
      - run: npm ci
      - run: npx run-s init bundle test-unit-bun
